version: '3.8'
name: personal-site
services:
  personal-site:
    restart: unless-stopped
    ports:
      - "7000:3000"
    image: ghcr.io/nixos/nix:2.31.3
    working_dir: /usr/src/app
    volumes:
      - /storage/docker-state/personal-site/:/usr/src/app
      - /storage/docker-state/jellyfin-stack/media/jellyfin-media/Photos/:/usr/src/app/static/assets/images
    command: nix develop --extra-experimental-features 'nix-command flakes' --command sh -c "cd static && make && cd .. && npm install && npm run preview"